export const en: any = {
  home: "home",
  setting: "setting",
  user_setting: "user setting",
  socials: "socials",
  add_social: "add social",
  twitter: "twitter",
  instagram: "instagram",
  telegram: "telegram",
  facebook: "facebook",
  edit: "edit",
  delete: "delete",
  type: "type",
  link: "link",
  cancel: "cancel",
  webSite: "webSite",
  linkedIn: "linkedIn",
  submit_btn: "submit button",
  textInputError: "it should be valid web address",
};
