export const fa: any = {
  home: "خانه",
  setting: "تنظیمات",
  user_setting: "تنظیمات کاربری",
  socials: "مسیرهای ارتباطی",
  add_social: "افزودن مسیر ارتباطی",
  twitter: "توییتر",
  instagram: "اینستاگرام",
  telegram: "تلگرام",
  facebook: "فیسبوک",
  edit: "ویرایش",
  delete: "حذف",
  type: "نوع",
  link: "لینک",
  cancel: "انصراف",
  webSite: "وبسایت",
  linkedIn: "لینکداین",
  submit_btn: "ثبت مسیر ارتباطی",
  textInputError: "محتویات این فیلد باید از جنس آدرس اینترنتی باشد.",
};
